//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSFeatureEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSFeatureEngine.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Action with the ID &apos;{0}&apos; could not be found in Feature &apos;{1}&apos;..
        /// </summary>
        internal static string ActionWithIdNotFoundInFeatureId {
            get {
                return ResourceManager.GetString("ActionWithIdNotFoundInFeatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not complete action..
        /// </summary>
        internal static string CouldNotCompleteAction {
            get {
                return ResourceManager.GetString("CouldNotCompleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine features in the specified project..
        /// </summary>
        internal static string CouldNotDetermineFeaturesInProject {
            get {
                return ResourceManager.GetString("CouldNotDetermineFeaturesInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load feature pack.
        /// </summary>
        internal static string CouldNotLoadFeaturePack {
            get {
                return ResourceManager.GetString("CouldNotLoadFeaturePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not obtain a project GUID..
        /// </summary>
        internal static string CouldNotObtainProjectGUID {
            get {
                return ResourceManager.GetString("CouldNotObtainProjectGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not unload all feature packs..
        /// </summary>
        internal static string CouldNotUnloadAllPacks {
            get {
                return ResourceManager.GetString("CouldNotUnloadAllPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not unload feature pack..
        /// </summary>
        internal static string CouldNotUnloadFeaturePack {
            get {
                return ResourceManager.GetString("CouldNotUnloadFeaturePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An extension with the id &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ExtensionIdNotFound {
            get {
                return ResourceManager.GetString("ExtensionIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Feature with the ID &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string FeatureWithIdNotFound {
            get {
                return ResourceManager.GetString("FeatureWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Item Template with the ID &apos;{0}&apos; could not be found in Feature &apos;{1}&apos;..
        /// </summary>
        internal static string ItemTemplateWithIdNotFoundInFeatureId {
            get {
                return ResourceManager.GetString("ItemTemplateWithIdNotFoundInFeatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A feature pack manifest ({0}) could not be found at the path &apos;{1}&apos;..
        /// </summary>
        internal static string MissingFeatureManifestAtPath {
            get {
                return ResourceManager.GetString("MissingFeatureManifestAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Project Template with the ID &apos;{0}&apos; could not be found in Feature &apos;{1}&apos;..
        /// </summary>
        internal static string ProjectTemplateWithIdNotFoundInFeatureId {
            get {
                return ResourceManager.GetString("ProjectTemplateWithIdNotFoundInFeatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; is required for feature actions..
        /// </summary>
        internal static string RequiredAttributeForAction {
            get {
                return ResourceManager.GetString("RequiredAttributeForAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; is required for code based feature actions..
        /// </summary>
        internal static string RequiredAttributeForCodeAction {
            get {
                return ResourceManager.GetString("RequiredAttributeForCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; is required for feature extensions..
        /// </summary>
        internal static string RequiredAttributeForExtension {
            get {
                return ResourceManager.GetString("RequiredAttributeForExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; could not be found in assembly &apos;{1}&apos;..
        /// </summary>
        internal static string TypeNameNotFoundInAssembly {
            get {
                return ResourceManager.GetString("TypeNameNotFoundInAssembly", resourceCulture);
            }
        }
    }
}
